/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.MapSense
{
    public class PlanarRegions : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "map_sense/PlanarRegions";

        public Header header;
        public float[] data;

        public PlanarRegions()
        {
            this.header = new Header();
            this.data = new float[0];
        }

        public PlanarRegions(Header header, float[] data)
        {
            this.header = header;
            this.data = data;
        }
    }
}