/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.MapSense
{
    public class PlanarRegion : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "map_sense/PlanarRegion";

        public Header header;
        public PolygonStamped polygon;
        public Point32 normal;

        public PlanarRegion()
        {
            this.header = new Header();
            this.polygon = new PolygonStamped();
            this.normal = new Point32();
        }

        public PlanarRegion(Header header, PolygonStamped polygon, Point32 normal)
        {
            this.header = header;
            this.polygon = polygon;
            this.normal = normal;
        }
    }
}
